### ISSUE TITLE
TextRenderer Widget throws "Unexpected null value." at using inside a Row or Column

### ISSUE THREAD

**Issue by weth767** [iamSahdeep/seo_renderer#13]
I'm trying to use TextRenderer inside to any Rows and Columns and always throws me error. But, the showed error don't say me what the problem, because, it's throwed a default error. 
**Any observations:**

- Flutter version: 2.10
- Seo_Renderer lib version: 0.0.5

**Example code:**

```flutter
Row(
  mainAxisAlignment: MainAxisAlignment.start,
  children: [
  InkWell(
    onTap: () {
      goToHomePage();
    },
    child: Container(
      width: 500,
      height: 200,
      child: TextRenderer(
        text: "Choose more products",
        style: SeoUtils.getTextRendererStyleByFontSize(14),
        child: Text(
          "Choose more products",
          style: TextStyle(
            fontSize: 14,
            color: const Color(0xFF3B3B3B),
            decoration: TextDecoration.underline,
            decorationColor: const Color(0xFF3B3B3B),
            fontWeight: FontWeight.bold,
          ),
        ),
      ),
    ),
  ),
  Container(child: Icon(Icons.add),),
  ],
  );
```

Follow below stack errors:

════════ Exception caught by widgets library ═══════════════════════════════════
The following TypeErrorImpl was thrown building TextRenderer(dirty, dependencies: [_ModalScopeStatus], state: _TextRendererState#a019f):
Unexpected null value.

The relevant error-causing widget was
TextRenderer
When the exception was thrown, this was the stack
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 251:49      throw_
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 528:63  nullCheck
packages/seo_renderer/helpers/robot_detector_web.dart 20:68                                                                    detected
packages/seo_renderer/renderers/text_renderer/text_renderer_web.dart 94:24                                                     build
packages/flutter/src/widgets/framework.dart 4870:27                                                                            build
packages/flutter/src/widgets/framework.dart 4754:15                                                                            performRebuild
packages/flutter/src/widgets/framework.dart 4928:11                                                                            performRebuild
packages/flutter/src/widgets/framework.dart 4477:5                                                                             rebuild
packages/flutter/src/widgets/framework.dart 4735:5                                                                             [_firstBuild]
packages/flutter/src/widgets/framework.dart 4919:11                                                                            [_firstBuild]
packages/flutter/src/widgets/framework.dart 4729:5                                                                             mount
packages/flutter/src/widgets/framework.dart 3790:13                                                                            inflateWidget
packages/flutter/src/widgets/framework.dart 3540:18                                                                            updateChild
packages/flutter/src/widgets/framework.dart 6284:14                                                                            mount
packages/flutter/src/widgets/framework.dart 3790:13                                                                            inflateWidget
packages/flutter/src/widgets/framework.dart 3540:18                                                                            updateChild
packages/flutter/src/widgets/framework.dart 4780:16                                                                            performRebuild
packages/flutter/src/widgets/framework.dart 4477:5                                                                             rebuild
packages/flutter/src/widgets/framework.dart 4735:5                                                                             [_firstBuild]
packages/flutter/src/widgets/framework.dart 4729:5                                                                             mount
packages/flutter/src/widgets/framework.dart 3790:13                                                                            inflateWidget
packages/flutter/src/widgets/framework.dart 3540:18                                                                            updateChild
packages/flutter/src/widgets/framework.dart 6284:14                                                                            mount
packages/flutter/src/widgets/framework.dart 3790:13                                                                            inflateWidget
packages/flutter/src/widgets/framework.dart 3540:18                                                                            updateChild
packages/flutter/src/widgets/framework.dart 4780:16                                                                            performRebuild
packages/flutter/src/widgets/framework.dart 4928:11                                                                            performRebuild
packages/flutter/src/widgets/framework.dart 4477:5                                                                             rebuild
packages/flutter/src/widgets/framework.dart 4735:5                                                                             [_firstBuild]
packages/flutter/src/widgets/framework.dart 4919:11                                                                            [_firstBuild]
packages/flutter/src/widgets/framework.dart 4729:5                                                                             mount
packages/flutter/src/widgets/framework.dart 3790:13                                                                            inflateWidget
packages/flutter/src/widgets/framework.dart 3540:18                                                                            updateChild
packages/flutter/src/widgets/framework.dart 4780:16                                                                            performRebuild
packages/flutter/src/widgets/framework.dart 4477:5                                                                             rebuild
packages/flutter/src/widgets/framework.dart 4735:5                                                                             [_firstBuild]
packages/flutter/src/widgets/framework.dart 4729:5                                                                             mount
packages/flutter/src/widgets/framework.dart 3790:13                                                                            inflateWidget
packages/flutter/src/widgets/framework.dart 3540:18                                                                            updateChild
packages/flutter/src/widgets/framework.dart 6284:14                                                                            mount
packages/flutter/src/widgets/framework.dart 3790:13                                                                            inflateWidget
packages/flutter/src/widgets/framework.dart 3540:18                                                                            updateChild
packages/flutter/src/widgets/framework.dart 6284:14                                                                            mount
packages/flutter/src/widgets/framework.dart 3790:13                                                                            inflateWidget
packages/flutter/src/widgets/framework.dart 3540:18                                                                            updateChild
packages/flutter/src/widgets/framework.dart 4780:16                                                                            performRebuild
packages/flutter/src/widgets/framework.dart 4928:11                                                                            performRebuild
packages/flutter/src/widgets/framework.dart 4477:5                                                                             rebuild
packages/flutter/src/widgets/framework.dart 4735:5                                                                             [_firstBuild]
packages/flutter/src/widgets/framework.dart 4919:11                                                                            [_firstBuild]
packages/flutter/src/widgets/framework.dart 4729:5                                                                             mount
packages/flutter/src/widgets/framework.dart 3790:13                                                                            inflateWidget
packages/flutter/src/widgets/framework.dart 3540:18                                                                            updateChild
packages/flutter/src/widgets/framework.dart 6284:14                                                                            mount
packages/flutter/src/widgets/framework.dart 3790:13                                                                            inflateWidget
packages/flutter/src/widgets/framework.dart 3540:18                                                                            updateChild
packages/flutter/src/widgets/framework.dart 4780:16                                                                            performRebuild
packages/flutter/src/widgets/framework.dart 4477:5                                                                             rebuild
packages/flutter/src/widgets/framework.dart 4735:5                                                                             [_firstBuild]
packages/flutter/src/widgets/framework.dart 4729:5                                                                             mount
packages/flutter/src/widgets/framework.dart 3790:13                                                                            inflateWidget
packages/flutter/src/widgets/framework.dart 3540:18                                                                            updateChild
packages/flutter/src/widgets/framework.dart 4780:16                                                                            performRebuild
packages/flutter/src/widgets/framework.dart 4928:11                                                                            performRebuild
packages/flutter/src/widgets/framework.dart 4477:5                                                                             rebuild
packages/flutter/src/widgets/framework.dart 4735:5                                                                             [_firstBuild]
packages/flutter/src/widgets/framework.dart 4919:11                                                                            [_firstBuild]
packages/flutter/src/widgets/framework.dart 4729:5                                                                             mount
packages/flutter/src/widgets/framework.dart 3790:13                                                                            inflateWidget
packages/flutter/src/widgets/framework.dart 3540:18                                                                            updateChild
packages/flutter/src/widgets/framework.dart 4780:16                                                                            performRebuild
packages/flutter/src/widgets/framework.dart 4477:5                                                                             rebuild
packages/flutter/src/widgets/framework.dart 4735:5                                                                             [_firstBuild]
packages/flutter/src/widgets/framework.dart 4729:5                                                                             mount
packages/flutter/src/widgets/framework.dart 3790:13                                                                            inflateWidget
packages/flutter/src/widgets/framework.dart 3540:18                                                                            updateChild
packages/flutter/src/widgets/framework.dart 4780:16                                                                            performRebuild
packages/flutter/src/widgets/framework.dart 4928:11                                                                            performRebuild
packages/flutter/src/widgets/framework.dart 4477:5                                                                             rebuild
packages/flutter/src/widgets/framework.dart 4735:5                                                                             [_firstBuild]
packages/flutter/src/widgets/framework.dart 4919:11                                                                            [_firstBuild]
packages/flutter/src/widgets/framework.dart 4729:5                                                                             mount
packages/flutter/src/widgets/framework.dart 3790:13                                                                            inflateWidget
packages/flutter/src/widgets/framework.dart 3540:18                                                                            updateChild
packages/flutter/src/widgets/framework.dart 4780:16                                                                            performRebuild
packages/flutter/src/widgets/framework.dart 4477:5                                                                             rebuild
packages/flutter/src/widgets/framework.dart 4735:5                                                                             [_firstBuild]
packages/flutter/src/widgets/framework.dart 4729:5                                                                             mount
packages/flutter/src/widgets/framework.dart 3790:13                                                                            inflateWidget
packages/flutter/src/widgets/framework.dart 3540:18                                                                            updateChild
packages/flutter/src/widgets/framework.dart 4780:16                                                                            performRebuild
packages/flutter/src/widgets/framework.dart 4928:11                                                                            performRebuild
packages/flutter/src/widgets/framework.dart 4477:5                                                                             rebuild
packages/flutter/src/widgets/framework.dart 4735:5                                                                             [_firstBuild]
packages/flutter/src/widgets/framework.dart 4919:11                                                                            [_firstBuild]
packages/flutter/src/widgets/framework.dart 4729:5                                                                             mount
packages/flutter/src/widgets/framework.dart 3790:13                                                                            inflateWidget
packages/flutter/src/widgets/framework.dart 3540:18                                                                            updateChild
packages/flutter/src/widgets/framework.dart 4780:16                                                                            performRebuild
packages/flutter/src/widgets/framework.dart 4477:5                                                                             rebuild
packages/flutter/src/widgets/framework.dart 4735:5                                                                             [_firstBuild]
packages/flutter/src/widgets/framework.dart 4729:5                                                                             mount
packages/flutter/src/widgets/framework.dart 3790:13                                                                            inflateWidget
packages/flutter/src/widgets/framework.dart 6422:36                                                                            inflateWidget
packages/flutter/src/widgets/framework.dart 6433:32                                                                            mount
packages/flutter/src/widgets/framework.dart 3790:13                                                                            inflateWidget
packages/flutter/src/widgets/framework.dart 3540:18                                                                            updateChild
packages/flutter/src/widgets/framework.dart 4780:16                                                                            performRebuild
packages/flutter/src/widgets/framework.dart 4928:11                                                                            performRebuild
packages/flutter/src/widgets/framework.dart 4477:5                                                                             rebuild
packages/flutter/src/widgets/framework.dart 4735:5                                                                             [_firstBuild]
packages/flutter/src/widgets/framework.dart 4919:11                                                                            [_firstBuild]
packages/flutter/src/widgets/framework.dart 4729:5                                                                             mount
packages/flutter/src/widgets/framework.dart 3790:13                                                                            inflateWidget
packages/flutter/src/widgets/framework.dart 6422:36                                                                            inflateWidget
packages/flutter/src/widgets/framework.dart 6433:32                                                                            mount
packages/flutter/src/widgets/framework.dart 3790:13                                                                            inflateWidget
packages/flutter/src/widgets/framework.dart 3540:18                                                                            updateChild
packages/flutter/src/widgets/framework.dart 6284:14                                                                            mount
packages/flutter/src/widgets/framework.dart 3790:13                                                                            inflateWidget
packages/flutter/src/widgets/framework.dart 3540:18                                                                            updateChild
packages/flutter/src/widgets/framework.dart 6284:14                                                                            mount
packages/flutter/src/widgets/framework.dart 3790:13                                                                            inflateWidget
packages/flutter/src/widgets/framework.dart 3540:18                                                                            updateChild
packages/flutter/src/widgets/framework.dart 6284:14                                                                            mount
packages/flutter/src/widgets/framework.dart 3790:13                                                                            inflateWidget
packages/flutter/src/widgets/framework.dart 3540:18                                                                            updateChild
packages/flutter/src/widgets/framework.dart 4780:16                                                                            performRebuild
packages/flutter/src/widgets/framework.dart 4477:5                                                                             rebuild
packages/flutter/src/widgets/framework.dart 4735:5                                                                             [_firstBuild]
packages/flutter/src/widgets/framework.dart 4729:5                                                                             mount
packages/flutter/src/widgets/framework.dart 3790:13                                                                            inflateWidget
packages/flutter/src/widgets/framework.dart 3540:18                                                                            updateChild
packages/flutter/src/widgets/framework.dart 6284:14                                                                            mount
packages/flutter/src/widgets/framework.dart 3790:13                                                                            inflateWidget
packages/flutter/src/widgets/framework.dart 3540:18                                                                            updateChild
packages/flutter/src/widgets/framework.dart 6284:14                                                                            mount
packages/flutter/src/widgets/framework.dart 3790:13                                                                            inflateWidget
packages/flutter/src/widgets/framework.dart 3540:18                                                                            updateChild
packages/flutter/src/widgets/framework.dart 4780:16                                                                            performRebuild
packages/flutter/src/widgets/framework.dart 4477:5                                                                             rebuild
packages/flutter/src/widgets/framework.dart 4735:5                                                                             [_firstBuild]
packages/flutter/src/widgets/framework.dart 4729:5                                                                             mount
packages/flutter/src/widgets/framework.dart 3790:13                                                                            inflateWidget
packages/flutter/src/widgets/framework.dart 3540:18                                                                            updateChild
packages/flutter/src/widgets/framework.dart 4780:16                                                                            performRebuild
packages/flutter/src/widgets/framework.dart 4477:5                                                                             rebuild
packages/flutter/src/widgets/framework.dart 4735:5                                                                             [_firstBuild]
packages/flutter/src/widgets/framework.dart 4729:5                                                                             mount
packages/flutter/src/widgets/framework.dart 3790:13                                                                            inflateWidget
packages/flutter/src/widgets/framework.dart 3540:18                                                                            updateChild
packages/flutter/src/widgets/framework.dart 4780:16                                                                            performRebuild
packages/flutter/src/widgets/framework.dart 4928:11                                                                            performRebuild
packages/flutter/src/widgets/framework.dart 4477:5                                                                             rebuild
packages/flutter/src/widgets/framework.dart 4735:5                                                                             [_firstBuild]
packages/flutter/src/widgets/framework.dart 4919:11                                                                            [_firstBuild]
packages/flutter/src/widgets/framework.dart 4729:5                                                                             mount
packages/flutter/src/widgets/framework.dart 3790:13                                                                            inflateWidget
packages/flutter/src/widgets/framework.dart 3540:18                                                                            updateChild
packages/flutter/src/widgets/framework.dart 4780:16                                                                            performRebuild
packages/flutter/src/widgets/framework.dart 4477:5                                                                             rebuild
packages/flutter/src/widgets/framework.dart 4735:5                                                                             [_firstBuild]
packages/flutter/src/widgets/framework.dart 4729:5                                                                             mount
packages/flutter/src/widgets/framework.dart 3790:13                                                                            inflateWidget
packages/flutter/src/widgets/framework.dart 3540:18                                                                            updateChild
packages/flutter/src/widgets/sliver.dart 1243:37                                                                               updateChild
packages/flutter/src/widgets/sliver.dart 1228:20                                                                               <fn>
packages/flutter/src/widgets/framework.dart 2600:19                                                                            buildScope
packages/flutter/src/widgets/sliver.dart 1221:5                                                                                createChild
packages/flutter/src/rendering/sliver_multi_box_adaptor.dart 349:23                                                            <fn>
packages/flutter/src/rendering/object.dart 1997:59                                                                             <fn>
packages/flutter/src/rendering/object.dart 918:15                                                                              [_enableMutationsToDirtySubtrees]
packages/flutter/src/rendering/object.dart 1997:7                                                                              invokeLayoutCallback
packages/flutter/src/rendering/sliver_multi_box_adaptor.dart 338:5                                                             [_createOrObtainChild]
packages/flutter/src/rendering/sliver_multi_box_adaptor.dart 484:5                                                             insertAndLayoutChild
packages/flutter/src/rendering/sliver_list.dart 239:19                                                                         advance
packages/flutter/src/rendering/sliver_list.dart 281:12                                                                         performLayout
packages/flutter/src/rendering/object.dart 1887:7                                                                              layout
packages/flutter/src/rendering/viewport.dart 510:12                                                                            layoutChildSequence
packages/flutter/src/rendering/viewport.dart 1580:12                                                                           [_attemptLayout]
packages/flutter/src/rendering/viewport.dart 1489:20                                                                           performLayout
packages/flutter/src/rendering/object.dart 1887:7                                                                              layout
packages/flutter/src/rendering/proxy_box.dart 116:7                                                                            performLayout
packages/flutter/src/rendering/object.dart 1887:7                                                                              layout
packages/flutter/src/rendering/proxy_box.dart 116:7                                                                            performLayout
packages/flutter/src/rendering/object.dart 1887:7                                                                              layout
packages/flutter/src/rendering/proxy_box.dart 116:7                                                                            performLayout
packages/flutter/src/rendering/object.dart 1887:7                                                                              layout
packages/flutter/src/rendering/proxy_box.dart 116:7                                                                            performLayout
packages/flutter/src/rendering/object.dart 1887:7                                                                              layout
packages/flutter/src/rendering/proxy_box.dart 116:7                                                                            performLayout
packages/flutter/src/rendering/object.dart 1887:7                                                                              layout
packages/flutter/src/rendering/proxy_box.dart 116:7                                                                            performLayout
packages/flutter/src/rendering/object.dart 1887:7                                                                              layout
packages/flutter/src/rendering/proxy_box.dart 116:7                                                                            performLayout
packages/flutter/src/rendering/object.dart 1887:7                                                                              layout
packages/flutter/src/rendering/proxy_box.dart 116:7                                                                            performLayout
packages/flutter/src/rendering/custom_paint.dart 545:11                                                                        performLayout
packages/flutter/src/rendering/object.dart 1887:7                                                                              layout
packages/flutter/src/rendering/proxy_box.dart 116:7                                                                            performLayout
packages/flutter/src/rendering/object.dart 1887:7                                                                              layout
packages/flutter/src/rendering/proxy_box.dart 116:7                                                                            performLayout
packages/flutter/src/rendering/object.dart 1887:7                                                                              layout
packages/flutter/src/rendering/proxy_box.dart 116:7                                                                            performLayout
packages/flutter/src/rendering/object.dart 1887:7                                                                              layout
packages/flutter/src/rendering/proxy_box.dart 116:7                                                                            performLayout
packages/flutter/src/rendering/object.dart 1887:7                                                                              layout
packages/flutter/src/rendering/custom_layout.dart 171:10                                                                       layoutChild
packages/flutter/src/material/scaffold.dart 1005:7                                                                             performLayout
packages/flutter/src/rendering/custom_layout.dart 240:7                                                                        [_callPerformLayout]
packages/flutter/src/rendering/custom_layout.dart 403:14                                                                       performLayout
packages/flutter/src/rendering/object.dart 1887:7                                                                              layout
packages/flutter/src/rendering/proxy_box.dart 116:7                                                                            performLayout
packages/flutter/src/rendering/object.dart 1887:7                                                                              layout
packages/flutter/src/rendering/proxy_box.dart 116:7                                                                            performLayout
packages/flutter/src/rendering/proxy_box.dart 1376:11                                                                          performLayout
packages/flutter/src/rendering/object.dart 1887:7                                                                              layout
packages/flutter/src/rendering/proxy_box.dart 116:7                                                                            performLayout
packages/flutter/src/rendering/object.dart 1887:7                                                                              layout
packages/flutter/src/rendering/proxy_box.dart 116:7                                                                            performLayout
packages/flutter/src/rendering/object.dart 1887:7                                                                              layout
packages/flutter/src/rendering/proxy_box.dart 116:7                                                                            performLayout
packages/flutter/src/rendering/object.dart 1887:7                                                                              layout
packages/flutter/src/rendering/proxy_box.dart 116:7                                                                            performLayout
packages/flutter/src/rendering/object.dart 1887:7                                                                              layout
packages/flutter/src/rendering/proxy_box.dart 116:7                                                                            performLayout
packages/flutter/src/rendering/object.dart 1887:7                                                                              layout
packages/flutter/src/rendering/proxy_box.dart 116:7                                                                            performLayout
packages/flutter/src/rendering/object.dart 1887:7                                                                              layout
packages/flutter/src/rendering/proxy_box.dart 116:7                                                                            performLayout
packages/flutter/src/rendering/object.dart 1887:7                                                                              layout
packages/flutter/src/rendering/proxy_box.dart 116:7                                                                            performLayout
packages/flutter/src/rendering/object.dart 1887:7                                                                              layout
packages/flutter/src/rendering/proxy_box.dart 116:7                                                                            performLayout
packages/flutter/src/rendering/proxy_box.dart 3430:13                                                                          performLayout
packages/flutter/src/rendering/object.dart 1887:7                                                                              layout
packages/flutter/src/rendering/proxy_box.dart 116:7                                                                            performLayout
packages/flutter/src/rendering/object.dart 1887:7                                                                              layout
packages/flutter/src/widgets/overlay.dart 751:14                                                                               performLayout
packages/flutter/src/rendering/object.dart 1887:7                                                                              layout
packages/flutter/src/rendering/proxy_box.dart 116:7                                                                            performLayout
packages/flutter/src/rendering/object.dart 1887:7                                                                              layout
packages/flutter/src/rendering/proxy_box.dart 116:7                                                                            performLayout
packages/flutter/src/rendering/object.dart 1887:7                                                                              layout
packages/flutter/src/rendering/proxy_box.dart 116:7                                                                            performLayout
packages/flutter/src/rendering/object.dart 1887:7                                                                              layout
packages/flutter/src/widgets/layout_builder.dart 321:7                                                                         performLayout
packages/flutter/src/rendering/object.dart 1887:7                                                                              layout
packages/flutter/src/rendering/custom_layout.dart 171:10                                                                       layoutChild
packages/flutter/src/material/scaffold.dart 1005:7                                                                             performLayout
packages/flutter/src/rendering/custom_layout.dart 240:7                                                                        [_callPerformLayout]
packages/flutter/src/rendering/custom_layout.dart 403:14                                                                       performLayout
packages/flutter/src/rendering/object.dart 1887:7                                                                              layout
packages/flutter/src/rendering/proxy_box.dart 116:7                                                                            performLayout
packages/flutter/src/rendering/object.dart 1887:7                                                                              layout
packages/flutter/src/rendering/proxy_box.dart 116:7                                                                            performLayout
packages/flutter/src/rendering/proxy_box.dart 1376:11                                                                          performLayout
packages/flutter/src/rendering/object.dart 1887:7                                                                              layout
packages/flutter/src/rendering/proxy_box.dart 116:7                                                                            performLayout
packages/flutter/src/rendering/object.dart 1731:7                                                                              [_layoutWithoutResize]
packages/flutter/src/rendering/object.dart 887:17                                                                              flushLayout
packages/flutter/src/rendering/binding.dart 497:19                                                                             drawFrame
packages/flutter/src/widgets/binding.dart 883:13                                                                               drawFrame
packages/flutter/src/rendering/binding.dart 363:5                                                                              [_handlePersistentFrameCallback]
packages/flutter/src/scheduler/binding.dart 1144:15                                                                            [_invokeFrameCallback]
packages/flutter/src/scheduler/binding.dart 1081:9                                                                             handleDrawFrame
packages/flutter/src/scheduler/binding.dart 995:5                                                                              [_handleDrawFrame]
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/platform_dispatcher.dart 1011:13               invoke
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/platform_dispatcher.dart 159:5                 invokeOnDrawFrame
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/initialization.dart 128:45                     <fn>
════════════════════════════════════════════════════════════════════════════════

**Comment by iamSahdeep** [comment]
Hi @weth767 
Seems like It can't find RobotDetector in the widget tree.

Have you added RobotDetector Widget like this? There are some changes in usage for v0.5.0
```
runApp(
  RobotDetector(
    debug: true, // you can set true to enable robot mode
    child: MaterialApp(
      home: MyApp(),
      navigatorObservers: [seoRouteObserver],
    ),
  ),
);
```

caused by : 
`context.findAncestorStateOfType<_RobotDetectorState>()!._detected;`

**Comment by weth767** [comment]
@iamSahdeep This was the cause. My problem was that RobotDetector it was added in ModularApp and not in MaterialApp, because i used Flutter Modular. Thanks for your help.
