### ISSUE TITLE
Use isbot package to detect robot

### ISSUE THREAD

**Issue by krokyze** [iamSahdeep/seo_renderer#15]
Potentially it could be better to use something like this https://www.npmjs.com/package/isbot to detect the robot:

```html
<script>
  if (isbot(navigator.userAgent)) {
    window.flutterWebRenderer = "html";
  }
</script>
```

And pass simple boolean down to `RobotDetector` dart code, just that I'm not that familiar with NPM and how to use it within html.

**Comment by iamSahdeep** [comment]
@krokyze Is it for users to enable html as web renderer?
Or should we use it to detect bot? internally it seems like this package is also using regexp from list of predefined bots mentioned in the list here https://github.com/omrilotan/isbot/blob/main/src/list.json

**Comment by krokyze** [comment]
@iamSahdeep yep that would then be used to detect the bot, and we wouldn't need to have the same regex in dart code.

**Comment by clragon** [comment]
adding a package like that to a flutter web project sounds tedious;
borrowing their regex list would be quite easy though.

**Comment by krokyze** [comment]
> adding a package like that to a flutter web project sounds tedious; borrowing their regex list would be quite easy though.

I feel copy pasting one of 100 available StackOverflow solutions is not ideal as no one has time to keep track of new robots appearing.

But as after some discussions in #1 seems like robot detection isn't quite valid solution so I'm closing this idea.
