### ISSUE TITLE
Div's positioning 

### ISSUE THREAD

**Issue by indigothm** [iamSahdeep/seo_renderer#2]
Is there any reason why the elements are added using an absolute position? It shouldn't affect SEO, am I wrong?

**Comment by iamSahdeep** [comment]
Yes, absolute position or maintaining the regular html flow should have same seo effects. I know that html should follow the flow, but just to be on safer side and have same UI I used absolute position and width for it.
I might be wrong Do you have any suggestion about it? I am not very much into web/html.
