### ISSUE TITLE
Can not detect GoogleBot userAgent in Network Condition and refresh the page to see created Div Elements.

### ISSUE THREAD

**Issue by esc-0-bar** [iamSahdeep/seo_renderer#24]
I'm wrapping my MaterialApp with RobotDetector and Text widgets with TextRenderer.
But when I Inspect Elements with GoogleBot userAgent, there is no extra html div's created by [seo_renderer] which google's bot gonna detect.

Which is mentioned in your app [](https://seo-renderer.netlify.app) .

**Comment by esc-0-bar** [comment]
This issue was caused by wrong widget imports.
We must import **seo_renderer.dart** instead of **text_renderer_style.dart and** **text_renderer_vm.dart**

**Comment by ljmatan** [comment]
For me, I've noticed that `html.window.navigator.userAgent` still returns the original user agent even though I've used [this extension for chrome](https://chrome.google.com/webstore/detail/user-agent-switcher-for-c/djflhoibgkdhkhhcedjiklpkjnoahfmg) which seems to work just fine.
