### ISSUE TITLE
Would you like to make this a Flutter Bounty Hunters project?

### ISSUE THREAD

**Issue by matthew-carroll** [iamSahdeep/seo_renderer#26]
Hi, I came across this package and it seems like an interesting direction for search indexing of Flutter webpages.

At the Flutter Bounty Hunters, we've been working on document editors and renderers in Super Editor. We also build our webpages with Flutter for web. This project looks like it would make sense within that ecosystem.

If you'd like to chat about migrating this project into our portfolio, and then working on getting funding for it, please let me know. You can respond here, or send me a [DM on twitter](https://twitter.com/suprdeclarative), or message me at https://flutterbountyhunters.com

**Comment by iamSahdeep** [comment]
Hi @matthew-carroll thanks for the offer, but I am not maintaining it anymore :(

**Comment by matthew-carroll** [comment]
Is someone else maintaining this package? Or is the package dead? If it's dead, can you let me know why you decided to shut it down?

**Comment by matthew-carroll** [comment]
I see you updated the README. I'll make this same offer on that other project. Thanks.

**Comment by iamSahdeep** [comment]
Yes, I can’t maintain it due to some personal reasons. But yeah that package is i guess will be maintained by the owner.
Thanks again 😄
