### ISSUE TITLE
Why doesn't there exists not html tag but only canvas tag?

### ISSUE THREAD

**Issue by changgyu-brandi** [iamSahdeep/seo_renderer#8]
Hi iamSahdeep.
I tried running your sample in your library, but couldn't find the difference  in chrome developer's tool.
I want to know if it is working for now.
There is no div tag when I run this project.

**Comment by rickypid** [comment]
Hi @changgyu-brandi ,

to see the change using the example provided it is necessary to change the type of user agent.  followed this [example](https://www.google.com/amp/s/winaero.com/change-user-agent-chrome/) and setting on Google bot
